# ZeroER results

- Configurations selected in [the tuning notebook](hyperparameter-tuning.ipynb)
- Unsupervised ZeroER refits on full candidate sets; embedding models stay pretrained
- Stored results by default; enable `RUN_*` for missing refits
- Mean full-gold F1 across operating points; blocking misses included
- Complementary halves: separate EM refits
- **Development results:** full data includes tuning pairs; directional splits overlap
- Experiment numbers match the tuning notebook; blocking results shown there

In [1]:
import functools
import sqlite3
from pathlib import Path

import numpy as np
import optuna
import pandas as pd
from IPython.display import display

from zeroer.config import MATCHING_STORAGE, OUTPUT_DIR, STORAGE
from zeroer.data.benchmarks import DATASETS
from zeroer.reporting.tables import show_table, study_status

optuna.logging.set_verbosity(optuna.logging.WARNING)
pd.set_option("display.max_columns", 20)
pd.set_option("display.max_colwidth", None)
SHOW_PLOTS = False

matching_db = sqlite3.connect((Path(OUTPUT_DIR) / "optuna_matching.db").resolve().as_uri() + "?mode=ro", uri=True)

### SQL inputs

- Read-only connections; temporary views
- Optuna categories decoded from stored choices
- Per-fit scores computed from raw counts

In [2]:
matching_db.executescript("""

CREATE TEMP VIEW IF NOT EXISTS decoded_params AS
SELECT trial_id, param_name,
       CASE json_extract(distribution_json, '$.name')
           WHEN 'CategoricalDistribution' THEN json_extract(distribution_json,
               '$.attributes.choices[' || CAST(param_value AS INTEGER) || ']')
           ELSE param_value
       END AS value
FROM trial_params;

CREATE TEMP VIEW IF NOT EXISTS result_trials AS
WITH parameters AS (
    SELECT trial_id, json_group_object(param_name, value) AS params
    FROM decoded_params GROUP BY trial_id
), attributes AS (
    SELECT trial_id, json_group_object(key, json(value_json)) AS attrs
    FROM trial_user_attributes GROUP BY trial_id
), experiments(experiment) AS (
    VALUES ('blocking'), ('ladder'), ('collapse'), ('match-zero'),
           ('match-missing'), ('emb-sweep'), ('emb-tune'),
           ('emb-cosine'), ('emb-cosine-tune')
), named AS (
    SELECT *, CASE WHEN study_name GLOB '*_full' THEN 'full' ELSE 'tuning' END AS phase,
           CASE WHEN study_name GLOB '*_full' THEN substr(study_name, 1, length(study_name)-5)
                ELSE study_name END AS base_name
    FROM studies
)
SELECT substr(s.base_name, 1, length(s.base_name)-length(e.experiment)-1) AS dataset,
       e.experiment, s.phase, t.trial_id, t.number, t.state,
       v.value AS mean_f1, p.params, a.attrs
FROM named s JOIN experiments e ON s.base_name GLOB '*_' || e.experiment
JOIN trials t USING (study_id)
LEFT JOIN trial_values v ON v.trial_id=t.trial_id AND v.objective=0
LEFT JOIN parameters p ON p.trial_id=t.trial_id
LEFT JOIN attributes a ON a.trial_id=t.trial_id;

CREATE TEMP VIEW IF NOT EXISTS embedding_results AS
SELECT r.*, json_extract(attrs, '$.rule') AS rule,
       json_extract(attrs, '$.selection') AS selection,
       json_extract(attrs, '$.source_trial') AS source_trial,
       json_extract(attrs, '$.n_models') AS n_models,
       json_extract(params, '$.fusion') AS fusion,
       coalesce((SELECT group_concat(model, ' + ') FROM (
           SELECT substr(param_name, 5) AS model FROM decoded_params
           WHERE trial_id=r.trial_id AND substr(param_name, 1, 4)='use_' AND value=1
           ORDER BY param_name
       )), 'strings only') AS models
FROM result_trials r
WHERE experiment IN ('emb-sweep', 'emb-tune', 'emb-cosine', 'emb-cosine-tune') AND state='COMPLETE';

CREATE TEMP VIEW IF NOT EXISTS matching_fits AS
SELECT r.dataset, r.experiment, r.phase, r.number,
       json_extract(r.attrs, '$.selection') AS selection,
       CASE a.key WHEN 'holdout_rungs' THEN 'complementary half' ELSE r.phase END AS scope,
       json_extract(f.value, '$.queried_side') AS queried_side,
       json_extract(f.value, '$.top_k') AS top_k,
       2.0*json_extract(f.value, '$.tp') /
           nullif(json_extract(f.value, '$.predicted') + json_extract(f.value, '$.n_gold'), 0) AS f1,
       2.0*json_extract(f.value, '$.tp_blocking') /
           nullif(json_extract(f.value, '$.candset_size') + json_extract(f.value, '$.n_gold'), 0) AS accept_all_f1,
       2.0*json_extract(f.value, '$.tp_blocking') /
           nullif(json_extract(f.value, '$.tp_blocking') + json_extract(f.value, '$.n_gold'), 0) AS oracle_f1,
       json_extract(f.value, '$.brier') AS brier,
       json_extract(f.value, '$.converged') AS converged,
       json_extract(f.value, '$.error') AS error
FROM result_trials r JOIN json_each(r.attrs) a ON a.key IN ('rungs', 'holdout_rungs')
JOIN json_each(a.value) f
WHERE r.state='COMPLETE';
""")

## 2. String baselines

- `optuna_matching.db`: `*_ladder` and `*_collapse`
- Baseline and diagnostic run settings: tuning notebook
- Candidate-precision operating points; PC ≥ 90% coverage below
- Failed fits: F1 = 0

In [3]:
BASELINE_NAMES = ["B-paper", "B-code"]

### Baselines and coverage

In [4]:
from zeroer.reporting.tables import ladder_frame, plot_ladder

CELL = ["dataset", "queried_side", "top_k"]
ladder = ladder_frame()
reference = ladder[ladder.config.isin(BASELINE_NAMES)]
reference_rungs = reference[reference.rung]
candidate_sets = reference_rungs.drop_duplicates(CELL)
controls = candidate_sets.groupby("dataset")[["accept_all_f1", "floor_f1", "oracle_f1"]].mean()
controls = controls.rename(columns={"floor_f1": "cosine_1to1_f1"})

baseline_scores = (reference_rungs.assign(f1=reference_rungs.f1.fillna(0))
                   .groupby(["dataset", "config"]).f1.mean().unstack("config"))
show_table(baseline_scores.join(controls))
show_table(candidate_sets.set_index(CELL)[["candset_size", "PC", "PQ"]]
           .assign(PC_at_least_90=lambda frame: frame.PC >= .90))
if SHOW_PLOTS:
    plot_ladder(reference)

,B-code,B-paper,accept_all_f1,cosine_1to1_f1,oracle_f1
dataset,,,,,
abt_buy,0.0352,0.1861,0.4819,0.9028,0.9642
amazon_googleproducts,0.0797,0.1867,0.4022,0.6523,0.9080
dblp_acm,0.9141,0.8564,0.4956,0.9879,0.9988
dblp_scholar,0.6777,0.7103,0.3996,0.5983,0.8835
fodors_zagats,0.9586,0.9896,0.3363,0.6599,1.0000

                                          candset_size      PC      PQ  \
dataset               queried_side top_k
abt_buy               left         1              1081  0.8250  0.8372
                                   2              2162  0.9225  0.4681
                                   13            14053  0.9973  0.0778
                      right        5              5460  0.9891  0.1987
amazon_googleproducts left         1              1363  0.6431  0.6134
                                   2              2726  0.8123  0.3874
                      right        2              6452  0.9223  0.1858
                                   5             16130  0.9862  0.0795
dblp_acm              left         1              2616  0.9937  0.8448
                                   2              5232  0.9982  0.4243
                      right        5             11470  0.9987  0.1936
                                   12            27528  1.0000  0.0808
dblp_scholar          left         1              2616  0.4440  0.9075
                                   5             13080  0.8999  0.3679
                                   10            26160  0.9761  0.1995
                      right        1             64263  0.9684  0.0806
fodors_zagats         left         1               533  1.0000  0.2101
                      right        1               331  1.0000  0.3384
                                   4              1324  1.0000  0.0846

                                          PC_at_least_90
dataset               queried_side top_k
abt_buy               left         1               False
                                   2                True
                                   13               True
                      right        5                True
amazon_googleproducts left         1               False
                                   2               False
                      right        2                True
                                   5                True
dblp_acm              left         1                True
                                   2                True
                      right        5                True
                                   12               True
dblp_scholar          left         1               False
                                   5               False
                                   10               True
                      right        1                True
fodors_zagats         left         1                True
                      right        1                True
                                   4                True

## 3. Parameter sensitivity

- Mean F1 across operating points
- Failed fits: F1 = 0

In [5]:
ladder = ladder_frame()
rungs = ladder[ladder.rung]
paper = rungs[rungs.config == "B-paper"].iloc[0]
SENSITIVITY_DATASETS = rungs[rungs.config.str.startswith(("c_bay=", "init_threshold="))].dataset.unique()
around = rungs[rungs.dataset.isin(SENSITIVITY_DATASETS) & ~rungs.transitivity
               & (rungs.tol == paper["tol"]) & (rungs.max_iter == paper["max_iter"])].copy()
around["failed"] = around.f1.isna()
around["f1"] = around.f1.fillna(0)
print("Mean F1 by c_bay; initialization threshold = 0.5")
show_table(around[around.init_threshold == paper["init_threshold"]]
           .groupby(["dataset", "c_bay"]).f1.mean().unstack("c_bay"))
print("Mean F1 by initialization threshold; c_bay = 0.01")
show_table(around[around.c_bay == paper["c_bay"]]
           .groupby(["dataset", "init_threshold"]).f1.mean().unstack("init_threshold"))
show_table(around.groupby("dataset").agg(fits=("f1", "size"), failed=("failed", "sum")))

Mean F1 by c_bay; initialization threshold = 0.5

c_bay                   0.000   0.001   0.010   0.030   0.100   0.300
dataset
abt_buy                0.1697  0.1983  0.1861  0.1283  0.0352  0.0000
amazon_googleproducts  0.1810  0.1751  0.1867  0.1882  0.1794  0.0072
dblp_scholar           0.4026  0.4855  0.7103  0.7220  0.7345  0.1392

Mean F1 by initialization threshold; c_bay = 0.01

init_threshold            0.2     0.3     0.4     0.5     0.6     0.7     0.8
dataset
abt_buy                0.2101  0.2011  0.1973  0.1861  0.1293  0.0774  0.0774
amazon_googleproducts  0.1867  0.1872  0.1872  0.1867  0.1867  0.0979  0.1103
dblp_scholar           0.5448  0.5465  0.7131  0.7103  0.6924  0.6698  0.6174

                       fits  failed
dataset
abt_buy                  48       0
amazon_googleproducts    48       3
dblp_scholar             48       3

## 4. Transitivity

- Mean F1 with / without the duplicate-free constraint
- DS excluded

In [6]:
ladder = ladder_frame()
TRANSITIVITY_DATASETS = ladder[ladder.config == "B-paper+transitivity"].dataset.unique()
trans = ladder[ladder.rung & ladder.config.isin(["B-paper", "B-paper+transitivity"])
               & ladder.dataset.isin(TRANSITIVITY_DATASETS)]
trans_scores = trans.groupby(["dataset", "config"]).f1.mean().unstack("config")
show_table(trans_scores.assign(gain=trans_scores["B-paper+transitivity"] - trans_scores["B-paper"]))

config                 B-paper  B-paper+transitivity    gain
dataset
abt_buy                 0.1861                0.0659 -0.1202
amazon_googleproducts   0.1867                0.2006  0.0139
dblp_acm                0.8564                0.9907  0.1342
fodors_zagats           0.9896                0.9940  0.0044

## 5. Missingness

- AB/AG: four operating points each; DA/DS: one control point each
- Failed fits: F1 = 0

In [7]:
from zeroer.reporting.tables import treatments_frame

show_table(study_status("collapse"))
collapse = treatments_frame(MATCHING_STORAGE)
collapse["failed"] = collapse.f1.isna()
collapse["score"] = collapse.f1.fillna(0)
show_table(collapse.groupby(["dataset", "config", "treatment"])
           .agg(mean_f1=("score", "mean"), fits=("score", "size"), failed=("failed", "sum")))

                            study  complete  failed  queued
0                abt_buy_collapse        26       6       0
1  amazon_googleproducts_collapse        32       0       0
2               dblp_acm_collapse         8       0       0
3           dblp_scholar_collapse         8       0       0

                                                         mean_f1  fits  failed
dataset               config  treatment
abt_buy               B-code  key_attribute               0.0263     4       3
                              key_attribute_mean_impute   0.0263     4       3
                              mean_impute                 0.0348     4       0
                              zero_fill                   0.0352     4       0
                      B-paper key_attribute               0.5498     4       0
                              key_attribute_mean_impute   0.5498     4       0
                              mean_impute                 0.2002     4       0
                              zero_fill                   0.1861     4       0
amazon_googleproducts B-code  key_attribute               0.5644     4       0
                              key_attribute_mean_impute   0.5644     4       0
                              mean_impute                 0.1650     4       0
                              zero_fill                   0.0797     4       0
                      B-paper key_attribute               0.4533     4       0
                              key_attribute_mean_impute   0.4533     4       0
                              mean_impute                 0.3769     4       0
                              zero_fill                   0.1867     4       0
dblp_acm              B-code  key_attribute               0.6595     1       0
                              key_attribute_mean_impute   0.6595     1       0
                              mean_impute                 0.9487     1       0
                              zero_fill                   0.9443     1       0
                      B-paper key_attribute               0.9383     1       0
                              key_attribute_mean_impute   0.9383     1       0
                              mean_impute                 0.9761     1       0
                              zero_fill                   0.9747     1       0
dblp_scholar          B-code  key_attribute               0.7128     1       0
                              key_attribute_mean_impute   0.7128     1       0
                              mean_impute                 0.7776     1       0
                              zero_fill                   0.5369     1       0
                      B-paper key_attribute               0.8351     1       0
                              key_attribute_mean_impute   0.8351     1       0
                              mean_impute                 0.8642     1       0
                              zero_fill                   0.7945     1       0

## 6. String refits

- `paper`: fixed B-paper; `donor`: other datasets' choice; `target`: own tuning winner
- Zero-fill and missing-aware likelihood
- Parameters from stored trials; shared fitting code
- `pi_M=seed`: initial match share (`None` in code)

In [8]:
import zeroer.model as module
from zeroer.experiments.tuning import replay_selected

module.tqdm = functools.partial(module.tqdm, disable=True)

MATCH_SEED = 0
# Fixed settings used by the stored searches; the five searched knobs come from the DB.
MATCH_FIXED = dict(tol=1e-5, max_iter=200)
TREATMENTS = {"match-zero": "zero", "match-missing": "ignore"}

/home/mda4172/Projects/data-env/lib/python3.10/site-packages/requests/__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (7.4.3)/charset_normalizer (3.4.5) doesn't match a supported version!
  warnings.warn(

In [9]:
from zeroer.reporting.tables import donor_selected, matching_rungs, matching_trials, replay_results

In [10]:
RUN_STRING_REPLAYS = False

if RUN_STRING_REPLAYS:
    for treatment, missing in TREATMENTS.items():
        trials = matching_trials(treatment)
        donors = donor_selected(trials).set_index("dataset").config_hash
        for dataset in DATASETS:
            own = trials[trials.dataset == dataset]
            chosen = {"paper": int(own[own.number == 0].iloc[0].number),
                      "donor": int(own[own.config_hash == donors[dataset]].iloc[0].number),
                      "target": int(own.loc[own.mean_f1.idxmax()].number)}
            full = replay_selected(dataset, treatment, chosen, fixed=MATCH_FIXED,
                                    missing=missing, seed=MATCH_SEED)
            print(f"{full.study_name}: " + "  ".join(
                f"{t.user_attrs['selection']}={t.value:.3f}" for t in full.trials))

### Full and complementary-half F1

- Accept-all and oracle bounds: each scope's gold and candidates

In [11]:
for treatment in TREATMENTS:
    print(treatment)
    show_table(study_status(treatment, full=True))
    show_table(replay_results(treatment))

match-zero

                                   study  complete  failed  queued
0                abt_buy_match-zero_full         3       0       0
1  amazon_googleproducts_match-zero_full         3       0       0
2               dblp_acm_match-zero_full         3       0       0
3           dblp_scholar_match-zero_full         3       0       0
4          fodors_zagats_match-zero_full         3       0       0

                                           donor   paper  target  \
dataset               scope
abt_buy               complementary half  0.0554  0.1570  0.4058
                      full                0.0386  0.1861  0.4134
amazon_googleproducts complementary half  0.1884  0.1884  0.1945
                      full                0.1867  0.1867  0.1924
dblp_acm              complementary half  0.8419  0.8419  0.8654
                      full                0.8564  0.8564  0.9161
dblp_scholar          complementary half  0.7053  0.7053  0.7322
                      full                0.7103  0.7103  0.7350
fodors_zagats         complementary half  0.9944  0.9944  0.9944
                      full                0.9896  0.9896  0.9911

                                          accept_all_f1  oracle_f1
dataset               scope
abt_buy               complementary half         0.4863     0.9659
                      full                       0.4819     0.9642
amazon_googleproducts complementary half         0.3995     0.9060
                      full                       0.4022     0.9080
dblp_acm              complementary half         0.4956     0.9984
                      full                       0.4956     0.9988
dblp_scholar          complementary half         0.4019     0.8852
                      full                       0.3996     0.8835
fodors_zagats         complementary half         0.3295     1.0000
                      full                       0.3363     1.0000

match-missing

                                      study  complete  failed  queued
0                abt_buy_match-missing_full         3       0       0
1  amazon_googleproducts_match-missing_full         3       0       0
2               dblp_acm_match-missing_full         3       0       0
3           dblp_scholar_match-missing_full         3       0       0
4          fodors_zagats_match-missing_full         3       0       0

                                           donor   paper  target  \
dataset               scope
abt_buy               complementary half  0.0539  0.3709  0.4979
                      full                0.0580  0.3775  0.5216
amazon_googleproducts complementary half  0.2157  0.2069  0.3004
                      full                0.2036  0.1993  0.3281
dblp_acm              complementary half  0.7276  0.8500  0.8629
                      full                0.7268  0.8612  0.8631
dblp_scholar          complementary half  0.6861  0.7004  0.7688
                      full                0.6731  0.6894  0.7684
fodors_zagats         complementary half  0.9612  0.9944  0.9944
                      full                0.9586  0.9896  0.9911

                                          accept_all_f1  oracle_f1
dataset               scope
abt_buy               complementary half         0.4863     0.9659
                      full                       0.4819     0.9642
amazon_googleproducts complementary half         0.3995     0.9060
                      full                       0.4022     0.9080
dblp_acm              complementary half         0.4956     0.9984
                      full                       0.4956     0.9988
dblp_scholar          complementary half         0.4019     0.8852
                      full                       0.3996     0.8835
fodors_zagats         complementary half         0.3295     1.0000
                      full                       0.3363     1.0000

### Winners and hyperparameters

In [12]:
rows = []
for treatment in TREATMENTS:
    trials = matching_trials(treatment, full=True)
    if not trials.empty:
        rows.append(trials[trials.selection == "target"].assign(treatment=treatment))
if rows:
    winners = pd.concat(rows).set_index(["treatment", "dataset"])
    winners["pi_M"] = winners.pi_M.map(lambda value: "seed" if pd.isna(value) else value)
    show_table(winners[["source_trial", "mean_f1", "c_bay", "init_threshold",
                         "init_statistic", "pi_M", "hard", "n_errors"]])
else:
    print("No string-only replays stored.")

                                     source_trial  mean_f1   c_bay  \
treatment     dataset
match-zero    fodors_zagats                    10   0.9911  0.0183
              dblp_acm                        146   0.9161  0.0134
              dblp_scholar                     35   0.7350  0.1167
              abt_buy                          82   0.4134  0.0001
              amazon_googleproducts           115   0.1924  0.0545
match-missing fodors_zagats                    10   0.9911  0.0183
              dblp_acm                        139   0.8631  0.0108
              dblp_scholar                    100   0.7684  0.1045
              abt_buy                         111   0.5216  0.0069
              amazon_googleproducts           120   0.3281  0.0031

                                     init_threshold init_statistic  pi_M  \
treatment     dataset
match-zero    fodors_zagats                  0.5903   present_mean   0.2
              dblp_acm                       0.7877   present_mean  0.05
              dblp_scholar                   0.2396   present_mean  0.05
              abt_buy                        0.2576   present_mean  seed
              amazon_googleproducts          0.4524   present_mean   0.2
match-missing fodors_zagats                  0.5903   present_mean   0.2
              dblp_acm                       0.7854   present_mean  seed
              dblp_scholar                   0.2054            sum  0.02
              abt_buy                        0.2621   present_mean   0.1
              amazon_googleproducts          0.2559            sum  seed

                                      hard  n_errors
treatment     dataset
match-zero    fodors_zagats           True         0
              dblp_acm                True         0
              dblp_scholar            True         0
              abt_buy                False         0
              amazon_googleproducts  False         0
match-missing fodors_zagats           True         0
              dblp_acm               False         0
              dblp_scholar           False         0
              abt_buy                 True         0
              amazon_googleproducts   True         0

## 7. Embedding refits

- Name/title strings + selected embedding panels
- Eight fixed rules, donor choice and target choice
- Fixed B-paper hyperparameters; joint tuning separate

In [13]:
KEY_ATTRIBUTE = {"abt_buy": "name", "fodors_zagats": "name"}

In [14]:
FIXED_RULES = ["strings", "all-20:separate", "all-20:mean", "all-20:zmean", "all-20:family",
               "one-per-family", "cheapest-3", "cheapest-5"]

In [15]:
RUN_EMBEDDING_REPLAYS = False

if RUN_EMBEDDING_REPLAYS:
    EXPERIMENT = "emb-sweep"
    trials = matching_trials(EXPERIMENT)
    donors = donor_selected(trials).set_index("dataset").config_hash
    for dataset in DATASETS:
        own = trials[trials.dataset == dataset]
        chosen = {rule: int(own[own.rule == rule].iloc[0].number) for rule in FIXED_RULES}
        chosen["donor"] = int(own[own.config_hash == donors[dataset]].iloc[0].number)
        chosen["target"] = int(own.loc[own.mean_f1.idxmax()].number)
        full = replay_selected(dataset, EXPERIMENT, chosen, fixed=MATCH_FIXED,
                                attributes=[KEY_ATTRIBUTE.get(dataset, "title")], seed=MATCH_SEED)
        print(f"{full.study_name}: " + "  ".join(
            f"{t.user_attrs['selection']}={t.value:.3f}" for t in full.trials))

### Replay runs

In [16]:
embedding_full_status = pd.read_sql_query("""
SELECT s.study_name AS study,
       sum(t.state='COMPLETE') AS complete, sum(t.state='FAIL') AS failed,
       sum(t.state='WAITING') AS queued
FROM studies s LEFT JOIN trials t USING (study_id)
WHERE s.study_name GLOB :pattern
GROUP BY s.study_name ORDER BY s.study_name
""", matching_db, params={'pattern': '*_emb-sweep_full'})
display(embedding_full_status)

                                  study  complete  failed  queued
0                abt_buy_emb-sweep_full        10       0       0
1  amazon_googleproducts_emb-sweep_full        10       0       0
2               dblp_acm_emb-sweep_full        10       0       0
3           dblp_scholar_emb-sweep_full        10       0       0
4          fodors_zagats_emb-sweep_full        10       0       0

### Full and complementary-half F1

In [17]:
panel_replays = pd.read_sql_query("""
SELECT dataset, scope, round(avg(CASE selection WHEN 'all-20:family' THEN f1 END), 4) AS "all-20:family",
       round(avg(CASE selection WHEN 'all-20:mean' THEN f1 END), 4) AS "all-20:mean",
       round(avg(CASE selection WHEN 'all-20:separate' THEN f1 END), 4) AS "all-20:separate",
       round(avg(CASE selection WHEN 'all-20:zmean' THEN f1 END), 4) AS "all-20:zmean",
       round(avg(CASE selection WHEN 'cheapest-3' THEN f1 END), 4) AS "cheapest-3",
       round(avg(CASE selection WHEN 'cheapest-5' THEN f1 END), 4) AS "cheapest-5",
       round(avg(CASE selection WHEN 'donor' THEN f1 END), 4) AS "donor",
       round(avg(CASE selection WHEN 'one-per-family' THEN f1 END), 4) AS "one-per-family",
       round(avg(CASE selection WHEN 'strings' THEN f1 END), 4) AS "strings",
       round(avg(CASE selection WHEN 'target' THEN f1 END), 4) AS "target",
       round(avg(accept_all_f1), 4) AS accept_all_f1, round(avg(oracle_f1), 4) AS oracle_f1
FROM matching_fits WHERE experiment='emb-sweep' AND phase='full'
GROUP BY dataset, scope ORDER BY dataset, scope
""", matching_db, index_col=['dataset', 'scope'])
display(panel_replays)

                                          all-20:family  all-20:mean  \
dataset               scope
abt_buy               complementary half         0.5387       0.5569
                      full                       0.5278       0.5419
amazon_googleproducts complementary half         0.4447       0.4495
                      full                       0.4360       0.4452
dblp_acm              complementary half         0.9360       0.9269
                      full                       0.9432       0.9341
dblp_scholar          complementary half         0.7754       0.7799
                      full                       0.7758       0.7816
fodors_zagats         complementary half         0.8906       0.8871
                      full                       0.8605       0.8469

                                          all-20:separate  all-20:zmean  \
dataset               scope
abt_buy               complementary half           0.4860        0.5568
                      full                         0.5018        0.5418
amazon_googleproducts complementary half           0.4537        0.4494
                      full                         0.4524        0.4452
dblp_acm              complementary half           0.9337        0.9269
                      full                         0.9441        0.9345
dblp_scholar          complementary half           0.7378        0.7797
                      full                         0.7415        0.7816
fodors_zagats         complementary half           0.8218        0.8871
                      full                         0.7830        0.8469

                                          cheapest-3  cheapest-5   donor  \
dataset               scope
abt_buy               complementary half      0.5402      0.5268  0.5330
                      full                    0.5322      0.5147  0.5156
amazon_googleproducts complementary half      0.4449      0.4741  0.4819
                      full                    0.4344      0.4347  0.4723
dblp_acm              complementary half      0.9312      0.9334  0.9361
                      full                    0.9394      0.9419  0.9460
dblp_scholar          complementary half      0.7769      0.7720  0.7658
                      full                    0.7768      0.7736  0.7673
fodors_zagats         complementary half      0.8906      0.8906  0.8906
                      full                    0.8547      0.8643  0.8489

                                          one-per-family  strings  target  \
dataset               scope
abt_buy               complementary half          0.5439   0.5578  0.5549
                      full                        0.5301   0.5498  0.5523
amazon_googleproducts complementary half          0.4323   0.4563  0.4464
                      full                        0.4243   0.4533  0.4480
dblp_acm              complementary half          0.9359   0.9206  0.9361
                      full                        0.9432   0.9268  0.9460
dblp_scholar          complementary half          0.7749   0.7733  0.7844
                      full                        0.7757   0.7747  0.7857
fodors_zagats         complementary half          0.9018   0.8836  0.9073
                      full                        0.8605   0.8469  0.8736

                                          accept_all_f1  oracle_f1
dataset               scope
abt_buy               complementary half         0.4863     0.9659
                      full                       0.4819     0.9642
amazon_googleproducts complementary half         0.3995     0.9060
                      full                       0.4022     0.9080
dblp_acm              complementary half         0.4956     0.9984
                      full                       0.4956     0.9988
dblp_scholar          complementary half         0.4019     0.8852
                      full                       0.3996     0.8835
fodors_zagats         complementary half         0.3295     1.0000
                      full                       0.3363     1.0000

### Refit winners

In [18]:
embedding_winners = pd.read_sql_query("""
SELECT f.dataset, f.source_trial, t.rule, f.models, f.fusion,
       round(t.mean_f1, 4) AS tuning_f1, round(f.mean_f1, 4) AS mean_f1
FROM embedding_results f JOIN embedding_results t
    ON t.dataset=f.dataset AND t.experiment=f.experiment AND t.phase='tuning' AND t.number=f.source_trial
WHERE f.experiment='emb-sweep' AND f.phase='full' AND f.selection='target'
ORDER BY f.dataset
""", matching_db, index_col='dataset')
display(embedding_winners)

,source_trial,rule,models,fusion,tuning_f1,mean_f1
dataset,,,,,,
abt_buy,201,pair:distilroberta+tencent_KaLM-Embedding-Gemma3-12B-2511,distilroberta + tencent_KaLM-Embedding-Gemma3-12B-2511,separate,0.5391,0.5523
amazon_googleproducts,173,pair:codefuse-ai_F2LLM-v2-4B+mpnet,codefuse-ai_F2LLM-v2-4B + mpnet,separate,0.4767,0.4480
dblp_acm,74,random-12:6,Octen_Octen-Embedding-8B + Qwen_Qwen3-Embedding-4B + bge_large + codefuse-ai_F2LLM-v2-14B + codefuse-ai_F2LLM-v2-8B + e5_instruct + e5_large_v2 + gtr_t5_large + minilm12 + minilm6 + mpnet + tencent_KaLM-Embedding-Gemma3-12B-2511,separate,0.9561,0.9460
dblp_scholar,87,pair:Octen_Octen-Embedding-8B+gte_large,Octen_Octen-Embedding-8B + gte_large,separate,0.7866,0.7857
fodors_zagats,74,random-12:6,Octen_Octen-Embedding-8B + Qwen_Qwen3-Embedding-4B + bge_large + codefuse-ai_F2LLM-v2-14B + codefuse-ai_F2LLM-v2-8B + e5_instruct + e5_large_v2 + gtr_t5_large + minilm12 + minilm6 + mpnet + tencent_KaLM-Embedding-Gemma3-12B-2511,separate,0.8532,0.8736

### Fit diagnostics

- Target winners; full candidate sets
- Candidate-level Brier score; capped = iteration limit

In [19]:
winner_diagnostics = pd.read_sql_query("""
SELECT dataset, selection, experiment, round(avg(brier), 4) AS brier, count(*) AS fits,
       sum(CASE WHEN converged=0 THEN 1 ELSE 0 END) AS capped,
       sum(error IS NOT NULL) AS failed
FROM matching_fits WHERE experiment IN ('match-zero', 'match-missing', 'emb-sweep')
    AND phase='full' AND scope='full' AND selection='target'
GROUP BY dataset, selection, experiment ORDER BY experiment, dataset
""", matching_db, index_col=['dataset', 'selection', 'experiment'])
display(winner_diagnostics)

                                                brier  fits  capped  failed
dataset               selection experiment
abt_buy               target    emb-sweep      0.2426     4       1       0
amazon_googleproducts target    emb-sweep      0.2613     4       1       0
dblp_acm              target    emb-sweep      0.0274     4       0       0
dblp_scholar          target    emb-sweep      0.0438     4       0       0
fodors_zagats         target    emb-sweep      0.0435     3       0       0
abt_buy               target    match-missing  0.3417     4       0       0
amazon_googleproducts target    match-missing  0.3063     4       2       0
dblp_acm              target    match-missing  0.0459     4       0       0
dblp_scholar          target    match-missing  0.0458     4       1       0
fodors_zagats         target    match-missing  0.0026     3       0       0
abt_buy               target    match-zero     0.5413     4       1       0
amazon_googleproducts target    match-zero     0.3196     4       0       0
dblp_acm              target    match-zero     0.0275     4       0       0
dblp_scholar          target    match-zero     0.0780     4       0       0
fodors_zagats         target    match-zero     0.0026     3       0       0

### Cosine-only refits

- All eligible attributes; one cosine per selected model × attribute
- Fixed panels and tuning-half winners; feature inputs restored from stored trial metadata
- Full and complementary-half ZeroER refits; embedders unchanged
- Constant columns dropped within each fit

In [20]:
def replay_cosine_selections(dataset, experiment):
    choices = pd.read_sql_query("""
    WITH candidates AS (
        SELECT * FROM embedding_results
        WHERE experiment=:experiment AND dataset=:dataset AND phase='tuning'
    ), targets AS (
        SELECT *, row_number() OVER (ORDER BY mean_f1 DESC, number) AS choice FROM candidates
    ), singles AS (
        SELECT *, row_number() OVER (ORDER BY mean_f1 DESC, number) AS choice
        FROM candidates WHERE n_models=1
    ), pairs AS (
        SELECT *, row_number() OVER (ORDER BY mean_f1 DESC, number) AS choice
        FROM candidates WHERE n_models=2
    ), all_models AS (
        SELECT *, row_number() OVER (ORDER BY mean_f1 DESC, number) AS choice
        FROM candidates WHERE n_models=20
    )
    SELECT 'target' AS selection, number FROM targets WHERE choice=1
    UNION ALL SELECT 'single', number FROM singles WHERE choice=1
    UNION ALL SELECT 'all-20:separate', number FROM all_models WHERE choice=1
    UNION ALL SELECT 'pair', number FROM pairs WHERE choice=1 AND :experiment='emb-cosine'
    UNION ALL SELECT rule, number FROM candidates
        WHERE :experiment='emb-cosine' AND rule IN ('one-per-family', 'cheapest-3', 'cheapest-5')
    """, matching_db, params={'experiment': experiment, 'dataset': dataset})
    if choices.empty:
        raise ValueError("Run cosine tuning before full-data refits")
    return replay_selected(dataset, experiment,
        dict(zip(choices.selection, choices.number.astype(int))),
        fixed=MATCH_FIXED if experiment == "emb-cosine" else {}, seed=MATCH_SEED)


RUN_COSINE_REPLAYS = False
if RUN_COSINE_REPLAYS:
    for dataset in DATASETS:
        replay_cosine_selections(dataset, "emb-cosine")

In [21]:
cosine_status = pd.read_sql_query("""
SELECT experiment, dataset, phase,
       sum(state='COMPLETE') AS complete, sum(state='FAIL') AS failed,
       sum(state='PRUNED') AS pruned, sum(state='WAITING') AS queued
FROM result_trials WHERE experiment IN ('emb-cosine', 'emb-cosine-tune')
GROUP BY experiment, dataset, phase ORDER BY experiment, dataset, phase
""", matching_db)
display(cosine_status)

,experiment,dataset,phase,complete,failed,pruned,queued
0,emb-cosine,abt_buy,full,7,0,0,0
1,emb-cosine,abt_buy,tuning,264,0,0,0
2,emb-cosine,amazon_googleproducts,full,7,0,0,0
3,emb-cosine,amazon_googleproducts,tuning,264,0,0,0
4,emb-cosine,dblp_acm,full,7,0,0,0
5,emb-cosine,dblp_acm,tuning,264,0,0,0
6,emb-cosine,dblp_scholar,full,7,0,0,0
7,emb-cosine,dblp_scholar,tuning,264,0,0,0
8,emb-cosine,fodors_zagats,full,7,0,0,0
9,emb-cosine,fodors_zagats,tuning,264,0,0,0
10,emb-cosine-tune,abt_buy,full,3,0,0,0
11,emb-cosine-tune,abt_buy,tuning,200,0,0,0
12,emb-cosine-tune,amazon_googleproducts,full,3,0,0,0
13,emb-cosine-tune,amazon_googleproducts,tuning,200,0,0,0
14,emb-cosine-tune,dblp_acm,full,3,0,0,0
15,emb-cosine-tune,dblp_acm,tuning,200,0,0,0
16,emb-cosine-tune,dblp_scholar,full,3,0,0,0
17,emb-cosine-tune,dblp_scholar,tuning,200,0,0,0
18,emb-cosine-tune,fodors_zagats,full,3,0,0,0
19,emb-cosine-tune,fodors_zagats,tuning,200,0,0,0

In [22]:
cosine_comparison = pd.read_sql_query("""
SELECT dataset, scope,
       round(avg(CASE WHEN experiment='emb-sweep' AND selection='strings' THEN f1 END), 4) AS key_strings,
       round(avg(CASE WHEN experiment='emb-sweep' AND selection='target' THEN f1 END), 4) AS key_strings_cosines,
       round(avg(CASE WHEN experiment='emb-cosine' AND selection='all-20:separate' THEN f1 END), 4) AS all20_cosines,
       round(avg(CASE WHEN experiment='emb-cosine' AND selection='single' THEN f1 END), 4) AS single_cosines,
       round(avg(CASE WHEN experiment='emb-cosine' AND selection='target' THEN f1 END), 4) AS selected_cosines,
       round(avg(CASE WHEN experiment='emb-cosine-tune' AND selection='target' THEN f1 END), 4) AS tuned_cosines
FROM matching_fits WHERE phase='full'
    AND experiment IN ('emb-sweep', 'emb-cosine', 'emb-cosine-tune')
GROUP BY dataset, scope ORDER BY dataset, scope
""", matching_db, index_col=['dataset', 'scope'])
display(cosine_comparison)

                                          key_strings  key_strings_cosines  \
dataset               scope
abt_buy               complementary half       0.5578               0.5549
                      full                     0.5498               0.5523
amazon_googleproducts complementary half       0.4563               0.4464
                      full                     0.4533               0.4480
dblp_acm              complementary half       0.9206               0.9361
                      full                     0.9268               0.9460
dblp_scholar          complementary half       0.7733               0.7844
                      full                     0.7747               0.7857
fodors_zagats         complementary half       0.8836               0.9073
                      full                     0.8469               0.8736

                                          all20_cosines  single_cosines  \
dataset               scope
abt_buy               complementary half         0.1991          0.2349
                      full                       0.2101          0.2457
amazon_googleproducts complementary half         0.0942          0.2729
                      full                       0.0911          0.3067
dblp_acm              complementary half         0.8956          0.9632
                      full                       0.8692          0.9680
dblp_scholar          complementary half         0.3888          0.5395
                      full                       0.3885          0.5425
fodors_zagats         complementary half         0.5995          0.7102
                      full                       0.5882          0.7087

                                          selected_cosines  tuned_cosines
dataset               scope
abt_buy               complementary half            0.3391         0.5896
                      full                          0.3461         0.6114
amazon_googleproducts complementary half            0.2352         0.5050
                      full                          0.2051         0.5178
dblp_acm              complementary half            0.9666         0.9884
                      full                          0.9715         0.9917
dblp_scholar          complementary half            0.5395         0.7975
                      full                          0.5425         0.8008
fodors_zagats         complementary half            0.7102         0.9824
                      full                          0.7087         0.9697

## 8. Tuned refits

- **Strings + name/title cosines**
- Joint search: **not run**
- Any stored refits shown below

### Joint replay runs

In [23]:
joint_full_status = pd.read_sql_query("""
SELECT s.study_name AS study,
       sum(t.state='COMPLETE') AS complete, sum(t.state='FAIL') AS failed,
       sum(t.state='WAITING') AS queued
FROM studies s LEFT JOIN trials t USING (study_id)
WHERE s.study_name GLOB :pattern
GROUP BY s.study_name ORDER BY s.study_name
""", matching_db, params={'pattern': '*_emb-tune_full'})
display(joint_full_status)

Empty DataFrame
Columns: [study, complete, failed, queued]
Index: []

### Joint results

In [24]:
joint_replays = pd.read_sql_query("""
SELECT dataset, scope, selection, round(avg(f1), 4) AS mean_f1,
       round(avg(accept_all_f1), 4) AS accept_all_f1, round(avg(oracle_f1), 4) AS oracle_f1
FROM matching_fits WHERE experiment='emb-tune' AND phase='full'
GROUP BY dataset, scope, selection ORDER BY dataset, scope, selection
""", matching_db)
display(joint_replays)

Empty DataFrame
Columns: [dataset, scope, selection, mean_f1, accept_all_f1, oracle_f1]
Index: []

### Cosine-only tuned refits

- Winner selected by tuning-half mean F1; all nine sampled ZeroER settings retained
- Full-data scores include tuning pairs; complementary halves retain directional overlap
- Earlier mixed-feature panels use name/title; these cosine-only panels use all eligible attributes

In [25]:
RUN_COSINE_TUNED_REPLAYS = False
if RUN_COSINE_TUNED_REPLAYS:
    for dataset in DATASETS:
        replay_cosine_selections(dataset, "emb-cosine-tune")

In [26]:
cosine_winners = pd.read_sql_query("""
WITH ranked AS (
    SELECT *, row_number() OVER (
        PARTITION BY experiment, dataset ORDER BY mean_f1 DESC, number) AS choice
    FROM embedding_results
    WHERE experiment IN ('emb-cosine', 'emb-cosine-tune') AND phase='tuning'
)
SELECT t.experiment, t.dataset, t.number, t.models, t.n_models,
       round(t.mean_f1, 4) AS tuning_f1, round(f.mean_f1, 4) AS full_f1
FROM ranked t LEFT JOIN embedding_results f
    ON f.dataset=t.dataset AND f.experiment=t.experiment AND f.phase='full'
   AND f.selection='target' AND f.source_trial=t.number
WHERE t.choice=1 ORDER BY t.experiment, t.dataset
""", matching_db, index_col=['experiment', 'dataset'])
display(cosine_winners)

                                       number  \
experiment      dataset
emb-cosine      abt_buy                    28
                amazon_googleproducts     227
                dblp_acm                  144
                dblp_scholar                6
                fodors_zagats               3
emb-cosine-tune abt_buy                   169
                amazon_googleproducts     176
                dblp_acm                   71
                dblp_scholar              112
                fodors_zagats             117

                                                                                                                                                                                                                                                           models  \
experiment      dataset
emb-cosine      abt_buy                                                                                                                                                                                               e5_large_v2 + microsoft_harrier-oss-v1-0.6b
                amazon_googleproducts                                                                                                                                                                          gte_large + tencent_KaLM-Embedding-Gemma3-12B-2511
                dblp_acm                                                                                                                                                                                       codefuse-ai_F2LLM-v2-14B + codefuse-ai_F2LLM-v2-4B
                dblp_scholar                                                                                                                                                                                                              codefuse-ai_F2LLM-v2-8B
                fodors_zagats                                                                                                                                                                                                                           bge_large
emb-cosine-tune abt_buy                                                                     Qwen_Qwen3-Embedding-4B + codefuse-ai_F2LLM-v2-4B + codefuse-ai_F2LLM-v2-8B + distilroberta + microsoft_harrier-oss-v1-0.6b + nvidia_llama-embed-nemotron-8b + st5_xl
                amazon_googleproducts  Octen_Octen-Embedding-8B + codefuse-ai_F2LLM-v2-14B + codefuse-ai_F2LLM-v2-4B + codefuse-ai_F2LLM-v2-8B + distilroberta + e5_instruct + e5_large_v2 + minilm12 + minilm6 + mpnet + nvidia_llama-embed-nemotron-8b + st5_xl
                dblp_acm                                                                                         Qwen_Qwen3-Embedding-4B + codefuse-ai_F2LLM-v2-4B + e5_instruct + microsoft_harrier-oss-v1-27b + st5_xl + tencent_KaLM-Embedding-Gemma3-12B-2511
                dblp_scholar                                                                                                                               Octen_Octen-Embedding-8B + codefuse-ai_F2LLM-v2-8B + e5_instruct + e5_large_v2 + gtr_t5_large + st5_xl
                fodors_zagats                                                                                                                                                                                              bge_large + e5_large_v2 + gtr_t5_large

                                       n_models  tuning_f1  full_f1
experiment      dataset
emb-cosine      abt_buy                       2     0.4202   0.3461
                amazon_googleproducts         2     0.3929   0.2051
                dblp_acm                      2     0.9757   0.9715
                dblp_scholar                  1     0.5419   0.5425
                fodors_zagats                 1     0.6988   0.7087
emb-cosine-tune abt_buy                       7     0.6034   0.6114
                amazon_googleproducts        12     0.5440   0.5178
                dblp_acm                      6     0.9918   0.9917
                dblp_scholar                  6     0.8006   0.8008
                fodors_zagats                 3     0.9826   0.9697

In [27]:
cosine_parameters = pd.read_sql_query("""
WITH ranked AS (
    SELECT *, row_number() OVER (PARTITION BY dataset ORDER BY mean_f1 DESC, number) AS choice
    FROM embedding_results WHERE experiment='emb-cosine-tune' AND phase='tuning'
)
SELECT dataset, number,
       json_extract(params, '$.c_bay') AS c_bay,
       json_extract(params, '$.init_threshold') AS init_threshold,
       json_extract(params, '$.init_statistic') AS init_statistic,
       coalesce(json_extract(params, '$.pi_M'), 'seed') AS pi_M,
       json_extract(params, '$.hard') AS hard,
       json_extract(params, '$.missing') AS missing,
       json_extract(params, '$.transitivity') AS transitivity,
       json_extract(params, '$.max_iter') AS max_iter,
       json_extract(params, '$.tol') AS tol,
       json_extract(attrs, '$.n_errors') AS failed_fits
FROM ranked WHERE choice=1 ORDER BY dataset
""", matching_db, index_col='dataset')
display(cosine_parameters)

,number,c_bay,init_threshold,init_statistic,pi_M,hard,missing,transitivity,max_iter,tol,failed_fits
dataset,,,,,,,,,,,
abt_buy,169,0.012309,0.645205,present_mean,0.02,1,ignore,0,200,0.000100,0
amazon_googleproducts,176,0.095244,0.260939,sum,0.02,1,ignore,0,200,0.000001,0
dblp_acm,71,0.093850,0.643650,present_mean,0.40,1,ignore,1,500,0.000100,0
dblp_scholar,112,0.124469,0.771432,present_mean,0.05,1,ignore,0,200,0.000100,0
fodors_zagats,117,0.023600,0.662973,sum,0.20,1,ignore,0,500,0.000010,0

In [28]:
cosine_comparison = pd.read_sql_query("""
SELECT dataset, scope,
       round(avg(CASE WHEN experiment='emb-sweep' AND selection='strings' THEN f1 END), 4) AS key_strings,
       round(avg(CASE WHEN experiment='emb-sweep' AND selection='target' THEN f1 END), 4) AS key_strings_cosines,
       round(avg(CASE WHEN experiment='emb-cosine' AND selection='all-20:separate' THEN f1 END), 4) AS all20_cosines,
       round(avg(CASE WHEN experiment='emb-cosine' AND selection='single' THEN f1 END), 4) AS single_cosines,
       round(avg(CASE WHEN experiment='emb-cosine' AND selection='target' THEN f1 END), 4) AS selected_cosines,
       round(avg(CASE WHEN experiment='emb-cosine-tune' AND selection='target' THEN f1 END), 4) AS tuned_cosines
FROM matching_fits WHERE phase='full'
    AND experiment IN ('emb-sweep', 'emb-cosine', 'emb-cosine-tune')
GROUP BY dataset, scope ORDER BY dataset, scope
""", matching_db, index_col=['dataset', 'scope'])
display(cosine_comparison)

                                          key_strings  key_strings_cosines  \
dataset               scope
abt_buy               complementary half       0.5578               0.5549
                      full                     0.5498               0.5523
amazon_googleproducts complementary half       0.4563               0.4464
                      full                     0.4533               0.4480
dblp_acm              complementary half       0.9206               0.9361
                      full                     0.9268               0.9460
dblp_scholar          complementary half       0.7733               0.7844
                      full                     0.7747               0.7857
fodors_zagats         complementary half       0.8836               0.9073
                      full                     0.8469               0.8736

                                          all20_cosines  single_cosines  \
dataset               scope
abt_buy               complementary half         0.1991          0.2349
                      full                       0.2101          0.2457
amazon_googleproducts complementary half         0.0942          0.2729
                      full                       0.0911          0.3067
dblp_acm              complementary half         0.8956          0.9632
                      full                       0.8692          0.9680
dblp_scholar          complementary half         0.3888          0.5395
                      full                       0.3885          0.5425
fodors_zagats         complementary half         0.5995          0.7102
                      full                       0.5882          0.7087

                                          selected_cosines  tuned_cosines
dataset               scope
abt_buy               complementary half            0.3391         0.5896
                      full                          0.3461         0.6114
amazon_googleproducts complementary half            0.2352         0.5050
                      full                          0.2051         0.5178
dblp_acm              complementary half            0.9666         0.9884
                      full                          0.9715         0.9917
dblp_scholar          complementary half            0.5395         0.7975
                      full                          0.5425         0.8008
fodors_zagats         complementary half            0.7102         0.9824
                      full                          0.7087         0.9697

In [29]:
cosine_full_diagnostics = pd.read_sql_query("""
SELECT dataset, experiment, round(avg(brier), 4) AS brier, count(*) AS fits,
       sum(CASE WHEN converged=0 THEN 1 ELSE 0 END) AS capped,
       sum(error IS NOT NULL) AS failed
FROM matching_fits WHERE experiment IN ('emb-cosine', 'emb-cosine-tune')
    AND phase='full' AND scope='full' AND selection='target'
GROUP BY dataset, experiment ORDER BY experiment, dataset
""", matching_db, index_col=['experiment', 'dataset'])
display(cosine_full_diagnostics)

                                        brier  fits  capped  failed
experiment      dataset
emb-cosine      abt_buy                0.5139     4       0       0
                amazon_googleproducts  0.3906     4       0       0
                dblp_acm               0.0145     4       0       0
                dblp_scholar           0.3457     4       0       0
                fodors_zagats          0.2164     3       0       0
emb-cosine-tune abt_buy                0.2634     4       0       0
                amazon_googleproducts  0.3314     4       0       0
                dblp_acm               0.0049     4       0       0
                dblp_scholar           0.0483     4       0       0
                fodors_zagats          0.0141     3       0       0

## Overall comparison

- Full candidate sets; mean full-gold F1 across the same operating points
- Target rows: refitted tuning winners; fixed rows: controls
- One-to-one: unsuitable for DS; constraint ablation on AB/AG

### Full-data F1

In [30]:
headline = pd.read_sql_query("""
WITH baseline AS (
    SELECT dataset, attrs FROM result_trials
    WHERE experiment='ladder' AND json_extract(attrs, '$.rung')=1
      AND json_extract(attrs, '$.config')='B-paper'
), scores AS (
    SELECT dataset, 1 AS position, 'B-paper: all string attributes' AS result,
           avg(coalesce(2.0*json_extract(attrs, '$.tp') /
               nullif(json_extract(attrs, '$.predicted')+json_extract(attrs, '$.n_gold'), 0), 0)) AS f1
    FROM baseline GROUP BY dataset
    UNION ALL
    SELECT dataset, CASE WHEN experiment='match-missing' AND selection='paper' THEN 2
                         WHEN experiment='match-missing' AND selection='target' THEN 3
                         WHEN experiment='emb-sweep' AND selection='strings' THEN 4 ELSE 5 END,
           CASE WHEN experiment='match-missing' AND selection='paper' THEN 'Missing-aware: fixed settings'
                WHEN experiment='match-missing' AND selection='target' THEN 'Missing-aware: target-tuned'
                WHEN experiment='emb-sweep' AND selection='strings' THEN 'Name/title strings: fixed settings'
                ELSE 'Name/title + target-selected embeddings' END,
           avg(f1)
    FROM matching_fits WHERE phase='full' AND scope='full'
        AND ((experiment='match-missing' AND selection IN ('paper','target'))
          OR (experiment='emb-sweep' AND selection IN ('strings','target')))
    GROUP BY dataset, experiment, selection
    UNION ALL
    SELECT dataset, CASE experiment WHEN 'emb-cosine' THEN 5.1 ELSE 5.2 END,
           CASE experiment WHEN 'emb-cosine' THEN 'All-attribute cosines: selected panel'
                           ELSE 'All-attribute cosines: tuned panel and ZeroER' END,
           avg(f1)
    FROM matching_fits WHERE phase='full' AND scope='full' AND selection='target'
        AND experiment IN ('emb-cosine', 'emb-cosine-tune')
    GROUP BY dataset, experiment
    UNION ALL
    SELECT dataset, 6, 'Retrieval cosine + greedy one-to-one',
           avg(2.0*json_extract(attrs, '$.floor_tp') /
               nullif(json_extract(attrs, '$.floor_predicted')+json_extract(attrs, '$.n_gold'), 0))
    FROM baseline GROUP BY dataset
    UNION ALL
    SELECT dataset, 7, 'Accept every candidate',
           avg(2.0*json_extract(attrs, '$.tp_blocking') /
               nullif(json_extract(attrs, '$.candset_size')+json_extract(attrs, '$.n_gold'), 0))
    FROM baseline GROUP BY dataset
    UNION ALL
    SELECT dataset, 8, 'Perfect matcher on these candidates',
           avg(2.0*json_extract(attrs, '$.tp_blocking') /
               nullif(json_extract(attrs, '$.tp_blocking')+json_extract(attrs, '$.n_gold'), 0))
    FROM baseline GROUP BY dataset
)
SELECT result, round(avg(CASE dataset WHEN 'abt_buy' THEN f1 END), 4) AS "abt_buy",
       round(avg(CASE dataset WHEN 'amazon_googleproducts' THEN f1 END), 4) AS "amazon_googleproducts",
       round(avg(CASE dataset WHEN 'dblp_acm' THEN f1 END), 4) AS "dblp_acm",
       round(avg(CASE dataset WHEN 'dblp_scholar' THEN f1 END), 4) AS "dblp_scholar",
       round(avg(CASE dataset WHEN 'fodors_zagats' THEN f1 END), 4) AS "fodors_zagats"
FROM scores GROUP BY position, result ORDER BY position
""", matching_db, index_col='result')
display(headline)

,abt_buy,amazon_googleproducts,dblp_acm,dblp_scholar,fodors_zagats
result,,,,,
B-paper: all string attributes,0.1861,0.1867,0.8564,0.7103,0.9896
Missing-aware: fixed settings,0.3775,0.1993,0.8612,0.6894,0.9896
Missing-aware: target-tuned,0.5216,0.3281,0.8631,0.7684,0.9911
Name/title strings: fixed settings,0.5498,0.4533,0.9268,0.7747,0.8469
Name/title + target-selected embeddings,0.5523,0.4480,0.9460,0.7857,0.8736
All-attribute cosines: selected panel,0.3461,0.2051,0.9715,0.5425,0.7087
All-attribute cosines: tuned panel and ZeroER,0.6114,0.5178,0.9917,0.8008,0.9697
Retrieval cosine + greedy one-to-one,0.9028,0.6523,0.9879,0.5983,0.6599
Accept every candidate,0.4819,0.4022,0.4956,0.3996,0.3363
Perfect matcher on these candidates,0.9642,0.9080,0.9988,0.8835,1.0000